name: Windows EXE Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg via Chocolatey and prepare bin
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          choco install ffmpeg -y --no-progress
          New-Item -ItemType Directory -Force -Path bin | Out-Null
          Copy-Item "$env:ChocolateyInstall\bin\ffmpeg.exe" bin\ffmpeg.exe -Force
          Copy-Item "$env:ChocolateyInstall\bin\ffprobe.exe" bin\ffprobe.exe -Force

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          if (Test-Path dist)  { Remove-Item -Recurse -Force dist }
          if (Test-Path app.spec) { Remove-Item -Force app.spec }
          pyinstaller `
            --name video_slicer `
            --onefile `
            --noconsole `
            --add-data "README.md;." `
            --add-data "requirements.txt;." `
            --add-binary "bin/ffmpeg.exe;." `
            --add-binary "bin/ffprobe.exe;." `
            app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video_slicer-windows
          path: dist/video_slicer.exe

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/video_slicer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
